### ISSUE TITLE
How to add multiple tags to --display-tags?

### ISSUE THREAD

**Issue by Baerbeisser** [ahjolinna/mpv-conf#12]
Sorry for the bother, hopefully a short thing.
Trying to remove/add multiple tags on cli, i get "Passing multiple arguments to display-tags-add is deprecated!".  
How should i do it then? Is there something like a meta string i could overwrite, similiar to the title?  
There's this section "String list and path list options" in manpage but i find nothing about it, neither on the internet.

(Btw, a separator line or '>' or something, for visuals, if playing multiple files (mpv *.ogg) would be nice)

**Comment by ahjolinna** [comment]
I have kinda abandoned/forgotten about this, as I don't use it anymore as I use [mpc-qt](https://mpc-qt.github.io/) nowdays

I have thought about redoing it but as many no time/interest/energy currently

but if you want to use mpv there are others confs you could look into for example: 
https://github.com/Tsubajashi/mpv-settings
or
https://github.com/noelsimbolon/mpv-config
