### ISSUE TITLE
BT.709 ICC source down

### ISSUE THREAD

**Issue by doobiebro** [ahjolinna/mpv-conf#4]
please re-upload, gracious ~master

**Comment by ahjolinna** [comment]
I uploaded it here: https://raw.githubusercontent.com/ahjolinna/mpv-conf/master/PKGBUILD/BT.709_Profiles.zip ...it was good luck that I had a backup of the file

**Comment by ahjolinna** [comment]
I will update the chakra's ccr pkgbuild when I have reinstalled chakraOS on my main system...(I broke the last installation)...I'm now using openSUSE leap 42.2 -kde...and I'm not responsible for the Arch/AUR version

**Comment by doobiebro** [comment]
No probs, I can build it myself from AUR with the new link.

Much appreciated ahjolinna
