### ISSUE TITLE
Depreciations i guess

### ISSUE THREAD

**Issue by SolarAquarion** [ahjolinna/mpv-conf#8]
Option fmt: unknown format name: '444p'
Error parsing option fmt (option parameter could not be parsed)
Option vf-add: Error while parsing noformat parameter fmt (444p)
Error parsing option vf-add (option parameter could not be parsed)
/etc/mpv/encoding-profiles.conf:72: setting option vf-add='noformat=444p,noformat=444p9,noformat=444p10,noformat=422p,noformat=422p9,noformat=422p10' failed.
Passing multiple arguments to ofopts-add is deprecated!
Passing multiple arguments to ovcopts-add is deprecated!
Passing multiple arguments to ofopts-add is deprecated!
Passing multiple arguments to ovcopts-add is deprecated!
Passing more than 1 argument to vf-add is deprecated!
Passing multiple arguments to ovcopts-add is deprecated!
Passing multiple arguments to ovcopts-add is deprecated!
Passing more than 1 argument to vf-add is deprecated!
Passing multiple arguments to ovcopts-add is deprecated!
Passing multiple arguments to ovcopts-add is deprecated!
Passing more than 1 argument to vf-add is deprecated!
Passing more than 1 argument to vf-add is deprecated!
Passing more than 1 argument to vf-add is deprecated!
Warning: option --sub-paths was replaced with --sub-file-paths and might be removed in the future.

**Comment by ahjolinna** [comment]
@SolarAquarion : yeah I notice that its broken again, I'm going to fix this and other things*  soon™...someday...I hope..sigh

when that's done I'm also planning to remake the pkgbuild

--------

*I'm interested to add some more features/scripts

------

input is always welcome

**Comment by ahjolinna** [comment]
@SolarAquarion : it should work now...I will soon "release" a newer version with these changes and a newer pkgbuild.

**Comment by ahjolinna** [comment]
I think I will release the next version of my conf when the next "stable" mpv is out
